name: Deploy to EC2 instance on

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs on Ubuntu runner in GitHub Actions

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/my-app
            git pull origin main  # Pull the latest changes (optional)
            # Copy your deployment files or scripts
            cp -r ./my-app /var/www/html/
            # Restart application, services, or Docker containers as needed
            sudo systemctl restart apache2  # Example, if you're using Apache web server
