name: Deploy to EC2 Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SSH into EC2 and Deploy to Minikube
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Run Kubernetes deployment commands
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
